apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
################# cart #################
- name: cart
  namespace: nongped
  envs: 
  - ./common/common.env
  - ./cart/cart.env
  
# Generator Option
generatorOptions:
  disableNameSuffixHash: true